export const SET_RECOMMENDATIONS = 'SET_RECOMMENDATIONS';
export const SET_NEW_EVENTS = 'SET_NEW_EVENtS';
export const SET_COMPILATIONS = 'SET_COMPILATIONS';
export const SET_FETCHING = 'SET_FETCHING';
